// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.0
// source: kurrentdb/protocols/v2/streams/shared.proto

package shared

import (
	_ "github.com/kurrent-io/KurrentDB-Client-Go/protos/kurrentdb/protocols/v2/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorDetails provides detailed information about specific error conditions.
type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0}
}

// When the user does not have sufficient permissions to perform the
// operation.
type ErrorDetails_AccessDenied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails_AccessDenied) Reset() {
	*x = ErrorDetails_AccessDenied{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_AccessDenied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_AccessDenied) ProtoMessage() {}

func (x *ErrorDetails_AccessDenied) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_AccessDenied.ProtoReflect.Descriptor instead.
func (*ErrorDetails_AccessDenied) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0, 0}
}

// When the stream has been deleted.
type ErrorDetails_StreamDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the stream that was deleted.
	Stream *string `protobuf:"bytes,1,opt,name=stream,proto3,oneof" json:"stream,omitempty"`
	// The time when the stream was deleted.
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails_StreamDeleted) Reset() {
	*x = ErrorDetails_StreamDeleted{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_StreamDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_StreamDeleted) ProtoMessage() {}

func (x *ErrorDetails_StreamDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_StreamDeleted.ProtoReflect.Descriptor instead.
func (*ErrorDetails_StreamDeleted) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ErrorDetails_StreamDeleted) GetStream() string {
	if x != nil && x.Stream != nil {
		return *x.Stream
	}
	return ""
}

func (x *ErrorDetails_StreamDeleted) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// When the stream has been tombstoned.
type ErrorDetails_StreamTombstoned struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the stream that was tombstoned.
	Stream *string `protobuf:"bytes,1,opt,name=stream,proto3,oneof" json:"stream,omitempty"`
	// The time when the stream was tombstoned.
	TombstonedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=tombstoned_at,json=tombstonedAt,proto3" json:"tombstoned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails_StreamTombstoned) Reset() {
	*x = ErrorDetails_StreamTombstoned{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_StreamTombstoned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_StreamTombstoned) ProtoMessage() {}

func (x *ErrorDetails_StreamTombstoned) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_StreamTombstoned.ProtoReflect.Descriptor instead.
func (*ErrorDetails_StreamTombstoned) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ErrorDetails_StreamTombstoned) GetStream() string {
	if x != nil && x.Stream != nil {
		return *x.Stream
	}
	return ""
}

func (x *ErrorDetails_StreamTombstoned) GetTombstonedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TombstonedAt
	}
	return nil
}

// When the stream is not found.
type ErrorDetails_StreamNotFound struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the stream that was not found.
	Stream        *string `protobuf:"bytes,1,opt,name=stream,proto3,oneof" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails_StreamNotFound) Reset() {
	*x = ErrorDetails_StreamNotFound{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_StreamNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_StreamNotFound) ProtoMessage() {}

func (x *ErrorDetails_StreamNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_StreamNotFound.ProtoReflect.Descriptor instead.
func (*ErrorDetails_StreamNotFound) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ErrorDetails_StreamNotFound) GetStream() string {
	if x != nil && x.Stream != nil {
		return *x.Stream
	}
	return ""
}

// When the expected revision of the stream does not match the actual
// revision.
type ErrorDetails_StreamRevisionConflict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual revision of the stream.
	StreamRevision int64 `protobuf:"varint,1,opt,name=stream_revision,json=streamRevision,proto3" json:"stream_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ErrorDetails_StreamRevisionConflict) Reset() {
	*x = ErrorDetails_StreamRevisionConflict{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_StreamRevisionConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_StreamRevisionConflict) ProtoMessage() {}

func (x *ErrorDetails_StreamRevisionConflict) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_StreamRevisionConflict.ProtoReflect.Descriptor instead.
func (*ErrorDetails_StreamRevisionConflict) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ErrorDetails_StreamRevisionConflict) GetStreamRevision() int64 {
	if x != nil {
		return x.StreamRevision
	}
	return 0
}

// When the transaction exceeds the maximum size allowed
// (its bigger than the configured chunk size).
type ErrorDetails_TransactionMaxSizeExceeded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum allowed size of the transaction.
	MaxSize       uint32 `protobuf:"varint,1,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails_TransactionMaxSizeExceeded) Reset() {
	*x = ErrorDetails_TransactionMaxSizeExceeded{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_TransactionMaxSizeExceeded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_TransactionMaxSizeExceeded) ProtoMessage() {}

func (x *ErrorDetails_TransactionMaxSizeExceeded) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_TransactionMaxSizeExceeded.ProtoReflect.Descriptor instead.
func (*ErrorDetails_TransactionMaxSizeExceeded) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ErrorDetails_TransactionMaxSizeExceeded) GetMaxSize() uint32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

// When the user is not found.
type ErrorDetails_UserNotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails_UserNotFound) Reset() {
	*x = ErrorDetails_UserNotFound{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_UserNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_UserNotFound) ProtoMessage() {}

func (x *ErrorDetails_UserNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_UserNotFound.ProtoReflect.Descriptor instead.
func (*ErrorDetails_UserNotFound) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0, 6}
}

// When the user is not authenticated.
type ErrorDetails_NotAuthenticated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails_NotAuthenticated) Reset() {
	*x = ErrorDetails_NotAuthenticated{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_NotAuthenticated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_NotAuthenticated) ProtoMessage() {}

func (x *ErrorDetails_NotAuthenticated) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_NotAuthenticated.ProtoReflect.Descriptor instead.
func (*ErrorDetails_NotAuthenticated) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0, 7}
}

type ErrorDetails_LogPositionNotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails_LogPositionNotFound) Reset() {
	*x = ErrorDetails_LogPositionNotFound{}
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_LogPositionNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_LogPositionNotFound) ProtoMessage() {}

func (x *ErrorDetails_LogPositionNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_LogPositionNotFound.ProtoReflect.Descriptor instead.
func (*ErrorDetails_LogPositionNotFound) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP(), []int{0, 8}
}

var File_kurrentdb_protocols_v2_streams_shared_proto protoreflect.FileDescriptor

const file_kurrentdb_protocols_v2_streams_shared_proto_rawDesc = "" +
	"\n" +
	"+kurrentdb/protocols/v2/streams/shared.proto\x12\x15kurrentdb.protocol.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/descriptor.proto\x1a!kurrentdb/protocols/v2/core.proto\"\xfd\t\n" +
	"\fErrorDetails\x1al\n" +
	"\fAccessDenied:\\\x82\xb5\x18X\n" +
	"\rACCESS_DENIED\x1aGThe user does not have sufficient permissions to perform the operation.\x1a\x87\x02\n" +
	"\rStreamDeleted\x12\x1b\n" +
	"\x06stream\x18\x01 \x01(\tH\x00R\x06stream\x88\x01\x01\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt:\x92\x01\x82\xb5\x18\x8d\x01\n" +
	"\x0eSTREAM_DELETED\x1a{The stream has been soft deleted. It will not be visible in the stream list, until it is restored by appending to it again.B\t\n" +
	"\a_stream\x1a\xd0\x01\n" +
	"\x10StreamTombstoned\x12\x1b\n" +
	"\x06stream\x18\x01 \x01(\tH\x00R\x06stream\x88\x01\x01\x12?\n" +
	"\rtombstoned_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ftombstonedAt:S\x82\xb5\x18O\n" +
	"\x11STREAM_TOMBSTONED\x1a:The stream has been tombstoned and cannot be used anymore.B\t\n" +
	"\a_stream\x1au\n" +
	"\x0eStreamNotFound\x12\x1b\n" +
	"\x06stream\x18\x01 \x01(\tH\x00R\x06stream\x88\x01\x01:;\x82\xb5\x187\n" +
	"\x10STREAM_NOT_FOUND\x1a#The specified stream was not found.B\t\n" +
	"\a_stream\x1a\xa0\x01\n" +
	"\x16StreamRevisionConflict\x12+\n" +
	"\x0fstream_revision\x18\x01 \x01(\x03B\x020\x01R\x0estreamRevision:Y\x82\xb5\x18U\n" +
	"\x11REVISION_CONFLICT\x1a@The actual stream revision does not match the expected revision.\x1a\x91\x01\n" +
	"\x1aTransactionMaxSizeExceeded\x12\x19\n" +
	"\bmax_size\x18\x01 \x01(\rR\amaxSize:X\x82\xb5\x18T\n" +
	"\x1dTRANSACTION_MAX_SIZE_EXCEEDED\x10\x01\x1a1The transaction exceeds the maximum size allowed.\x1aG\n" +
	"\fUserNotFound:7\x82\xb5\x183\n" +
	"\x0eUSER_NOT_FOUND\x1a!The specified user was not found.\x1aK\n" +
	"\x10NotAuthenticated:7\x82\xb5\x183\n" +
	"\x11NOT_AUTHENTICATED\x1a\x1eThe user is not authenticated.\x1a^\n" +
	"\x13LogPositionNotFound:G\x82\xb5\x18C\n" +
	"\x16LOG_POSITION_NOT_FOUND\x1a)The specified log position was not found.B\x9c\x01\n" +
	" io.kurrentdb.protocol.streams.v2P\x01ZVgithub.com/kurrent-io/KurrentDB-Client-Go/protos/kurrentdb/protocols/v2/streams/shared\xaa\x02\x1dKurrentDB.Protocol.Streams.V2b\x06proto3"

var (
	file_kurrentdb_protocols_v2_streams_shared_proto_rawDescOnce sync.Once
	file_kurrentdb_protocols_v2_streams_shared_proto_rawDescData []byte
)

func file_kurrentdb_protocols_v2_streams_shared_proto_rawDescGZIP() []byte {
	file_kurrentdb_protocols_v2_streams_shared_proto_rawDescOnce.Do(func() {
		file_kurrentdb_protocols_v2_streams_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kurrentdb_protocols_v2_streams_shared_proto_rawDesc), len(file_kurrentdb_protocols_v2_streams_shared_proto_rawDesc)))
	})
	return file_kurrentdb_protocols_v2_streams_shared_proto_rawDescData
}

var file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kurrentdb_protocols_v2_streams_shared_proto_goTypes = []any{
	(*ErrorDetails)(nil),                            // 0: kurrentdb.protocol.v2.ErrorDetails
	(*ErrorDetails_AccessDenied)(nil),               // 1: kurrentdb.protocol.v2.ErrorDetails.AccessDenied
	(*ErrorDetails_StreamDeleted)(nil),              // 2: kurrentdb.protocol.v2.ErrorDetails.StreamDeleted
	(*ErrorDetails_StreamTombstoned)(nil),           // 3: kurrentdb.protocol.v2.ErrorDetails.StreamTombstoned
	(*ErrorDetails_StreamNotFound)(nil),             // 4: kurrentdb.protocol.v2.ErrorDetails.StreamNotFound
	(*ErrorDetails_StreamRevisionConflict)(nil),     // 5: kurrentdb.protocol.v2.ErrorDetails.StreamRevisionConflict
	(*ErrorDetails_TransactionMaxSizeExceeded)(nil), // 6: kurrentdb.protocol.v2.ErrorDetails.TransactionMaxSizeExceeded
	(*ErrorDetails_UserNotFound)(nil),               // 7: kurrentdb.protocol.v2.ErrorDetails.UserNotFound
	(*ErrorDetails_NotAuthenticated)(nil),           // 8: kurrentdb.protocol.v2.ErrorDetails.NotAuthenticated
	(*ErrorDetails_LogPositionNotFound)(nil),        // 9: kurrentdb.protocol.v2.ErrorDetails.LogPositionNotFound
	(*timestamppb.Timestamp)(nil),                   // 10: google.protobuf.Timestamp
}
var file_kurrentdb_protocols_v2_streams_shared_proto_depIdxs = []int32{
	10, // 0: kurrentdb.protocol.v2.ErrorDetails.StreamDeleted.deleted_at:type_name -> google.protobuf.Timestamp
	10, // 1: kurrentdb.protocol.v2.ErrorDetails.StreamTombstoned.tombstoned_at:type_name -> google.protobuf.Timestamp
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_kurrentdb_protocols_v2_streams_shared_proto_init() }
func file_kurrentdb_protocols_v2_streams_shared_proto_init() {
	if File_kurrentdb_protocols_v2_streams_shared_proto != nil {
		return
	}
	file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[2].OneofWrappers = []any{}
	file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[3].OneofWrappers = []any{}
	file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kurrentdb_protocols_v2_streams_shared_proto_rawDesc), len(file_kurrentdb_protocols_v2_streams_shared_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kurrentdb_protocols_v2_streams_shared_proto_goTypes,
		DependencyIndexes: file_kurrentdb_protocols_v2_streams_shared_proto_depIdxs,
		MessageInfos:      file_kurrentdb_protocols_v2_streams_shared_proto_msgTypes,
	}.Build()
	File_kurrentdb_protocols_v2_streams_shared_proto = out.File
	file_kurrentdb_protocols_v2_streams_shared_proto_goTypes = nil
	file_kurrentdb_protocols_v2_streams_shared_proto_depIdxs = nil
}
