// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.0
// source: dynamic-value.proto

package dynamic_value

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamicValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*DynamicValue_NullValue
	//	*DynamicValue_Int32Value
	//	*DynamicValue_Int64Value
	//	*DynamicValue_BytesValue
	//	*DynamicValue_DoubleValue
	//	*DynamicValue_FloatValue
	//	*DynamicValue_StringValue
	//	*DynamicValue_BooleanValue
	//	*DynamicValue_TimestampValue
	//	*DynamicValue_DurationValue
	Kind          isDynamicValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicValue) Reset() {
	*x = DynamicValue{}
	mi := &file_dynamic_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicValue) ProtoMessage() {}

func (x *DynamicValue) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicValue.ProtoReflect.Descriptor instead.
func (*DynamicValue) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicValue) GetKind() isDynamicValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DynamicValue) GetNullValue() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_NullValue); ok {
			return x.NullValue
		}
	}
	return structpb.NullValue(0)
}

func (x *DynamicValue) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *DynamicValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *DynamicValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *DynamicValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *DynamicValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *DynamicValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *DynamicValue) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *DynamicValue) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *DynamicValue) GetDurationValue() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_DurationValue); ok {
			return x.DurationValue
		}
	}
	return nil
}

type isDynamicValue_Kind interface {
	isDynamicValue_Kind()
}

type DynamicValue_NullValue struct {
	// Represents a null value.
	NullValue structpb.NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

type DynamicValue_Int32Value struct {
	// Represents a 32-bit signed integer value.
	Int32Value int32 `protobuf:"zigzag32,2,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type DynamicValue_Int64Value struct {
	// Represents a 64-bit signed integer value.
	Int64Value int64 `protobuf:"zigzag64,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type DynamicValue_BytesValue struct {
	// Represents a byte array value.
	BytesValue []byte `protobuf:"bytes,4,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type DynamicValue_DoubleValue struct {
	// Represents a 64-bit double-precision floating-point value.
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type DynamicValue_FloatValue struct {
	// Represents a 32-bit single-precision floating-point value
	FloatValue float32 `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type DynamicValue_StringValue struct {
	// Represents a string value.
	StringValue string `protobuf:"bytes,7,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type DynamicValue_BooleanValue struct {
	// Represents a boolean value.
	BooleanValue bool `protobuf:"varint,8,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type DynamicValue_TimestampValue struct {
	// Represents a timestamp value.
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type DynamicValue_DurationValue struct {
	// Represents a duration value.
	DurationValue *durationpb.Duration `protobuf:"bytes,10,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

func (*DynamicValue_NullValue) isDynamicValue_Kind() {}

func (*DynamicValue_Int32Value) isDynamicValue_Kind() {}

func (*DynamicValue_Int64Value) isDynamicValue_Kind() {}

func (*DynamicValue_BytesValue) isDynamicValue_Kind() {}

func (*DynamicValue_DoubleValue) isDynamicValue_Kind() {}

func (*DynamicValue_FloatValue) isDynamicValue_Kind() {}

func (*DynamicValue_StringValue) isDynamicValue_Kind() {}

func (*DynamicValue_BooleanValue) isDynamicValue_Kind() {}

func (*DynamicValue_TimestampValue) isDynamicValue_Kind() {}

func (*DynamicValue_DurationValue) isDynamicValue_Kind() {}

var File_dynamic_value_proto protoreflect.FileDescriptor

const file_dynamic_value_proto_rawDesc = "" +
	"\n" +
	"\x13dynamic-value.proto\x12\x12kurrentdb.protobuf\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xdb\x03\n" +
	"\fDynamicValue\x12;\n" +
	"\n" +
	"null_value\x18\x01 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\tnullValue\x12!\n" +
	"\vint32_value\x18\x02 \x01(\x11H\x00R\n" +
	"int32Value\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x12H\x00R\n" +
	"int64Value\x12!\n" +
	"\vbytes_value\x18\x04 \x01(\fH\x00R\n" +
	"bytesValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vfloat_value\x18\x06 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fstring_value\x18\a \x01(\tH\x00R\vstringValue\x12%\n" +
	"\rboolean_value\x18\b \x01(\bH\x00R\fbooleanValue\x12E\n" +
	"\x0ftimestamp_value\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12B\n" +
	"\x0eduration_value\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationH\x00R\rdurationValueB\x06\n" +
	"\x04kindBUZ>github.com/kurrent-io/KurrentDB-Client-Go/protos/dynamic_value\xaa\x02\x12KurrentDB.Protobufb\x06proto3"

var (
	file_dynamic_value_proto_rawDescOnce sync.Once
	file_dynamic_value_proto_rawDescData []byte
)

func file_dynamic_value_proto_rawDescGZIP() []byte {
	file_dynamic_value_proto_rawDescOnce.Do(func() {
		file_dynamic_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynamic_value_proto_rawDesc), len(file_dynamic_value_proto_rawDesc)))
	})
	return file_dynamic_value_proto_rawDescData
}

var file_dynamic_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dynamic_value_proto_goTypes = []any{
	(*DynamicValue)(nil),          // 0: kurrentdb.protobuf.DynamicValue
	(structpb.NullValue)(0),       // 1: google.protobuf.NullValue
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 3: google.protobuf.Duration
}
var file_dynamic_value_proto_depIdxs = []int32{
	1, // 0: kurrentdb.protobuf.DynamicValue.null_value:type_name -> google.protobuf.NullValue
	2, // 1: kurrentdb.protobuf.DynamicValue.timestamp_value:type_name -> google.protobuf.Timestamp
	3, // 2: kurrentdb.protobuf.DynamicValue.duration_value:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dynamic_value_proto_init() }
func file_dynamic_value_proto_init() {
	if File_dynamic_value_proto != nil {
		return
	}
	file_dynamic_value_proto_msgTypes[0].OneofWrappers = []any{
		(*DynamicValue_NullValue)(nil),
		(*DynamicValue_Int32Value)(nil),
		(*DynamicValue_Int64Value)(nil),
		(*DynamicValue_BytesValue)(nil),
		(*DynamicValue_DoubleValue)(nil),
		(*DynamicValue_FloatValue)(nil),
		(*DynamicValue_StringValue)(nil),
		(*DynamicValue_BooleanValue)(nil),
		(*DynamicValue_TimestampValue)(nil),
		(*DynamicValue_DurationValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynamic_value_proto_rawDesc), len(file_dynamic_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dynamic_value_proto_goTypes,
		DependencyIndexes: file_dynamic_value_proto_depIdxs,
		MessageInfos:      file_dynamic_value_proto_msgTypes,
	}.Build()
	File_dynamic_value_proto = out.File
	file_dynamic_value_proto_goTypes = nil
	file_dynamic_value_proto_depIdxs = nil
}
