// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.0
// source: kurrentdb/protocols/v2/core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorAnnotations_Severity int32

const (
	// The error is recoverable, the operation failed but the session can continue.
	ErrorAnnotations_RECOVERABLE ErrorAnnotations_Severity = 0
	// The error is fatal and the session should be terminated.
	ErrorAnnotations_FATAL ErrorAnnotations_Severity = 1
)

// Enum value maps for ErrorAnnotations_Severity.
var (
	ErrorAnnotations_Severity_name = map[int32]string{
		0: "RECOVERABLE",
		1: "FATAL",
	}
	ErrorAnnotations_Severity_value = map[string]int32{
		"RECOVERABLE": 0,
		"FATAL":       1,
	}
)

func (x ErrorAnnotations_Severity) Enum() *ErrorAnnotations_Severity {
	p := new(ErrorAnnotations_Severity)
	*p = x
	return p
}

func (x ErrorAnnotations_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorAnnotations_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_kurrentdb_protocols_v2_core_proto_enumTypes[0].Descriptor()
}

func (ErrorAnnotations_Severity) Type() protoreflect.EnumType {
	return &file_kurrentdb_protocols_v2_core_proto_enumTypes[0]
}

func (x ErrorAnnotations_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorAnnotations_Severity.Descriptor instead.
func (ErrorAnnotations_Severity) EnumDescriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_core_proto_rawDescGZIP(), []int{0, 0}
}

type ErrorAnnotations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the error condition.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Severity of the error.
	Severity ErrorAnnotations_Severity `protobuf:"varint,2,opt,name=severity,proto3,enum=kurrentdb.protocol.ErrorAnnotations_Severity" json:"severity,omitempty"`
	// Human-readable message that describes the error condition.
	Message       *string `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorAnnotations) Reset() {
	*x = ErrorAnnotations{}
	mi := &file_kurrentdb_protocols_v2_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorAnnotations) ProtoMessage() {}

func (x *ErrorAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorAnnotations.ProtoReflect.Descriptor instead.
func (*ErrorAnnotations) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_core_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorAnnotations) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorAnnotations) GetSeverity() ErrorAnnotations_Severity {
	if x != nil {
		return x.Severity
	}
	return ErrorAnnotations_RECOVERABLE
}

func (x *ErrorAnnotations) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Represents a list of dynamically typed values.
type DynamicValueList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repeated property of dynamically typed values.
	Values        []*DynamicValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicValueList) Reset() {
	*x = DynamicValueList{}
	mi := &file_kurrentdb_protocols_v2_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicValueList) ProtoMessage() {}

func (x *DynamicValueList) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicValueList.ProtoReflect.Descriptor instead.
func (*DynamicValueList) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_core_proto_rawDescGZIP(), []int{1}
}

func (x *DynamicValueList) GetValues() []*DynamicValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// Represents a map of dynamically typed values.
type DynamicValueMap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map of string keys to dynamically typed values.
	Values        map[string]*DynamicValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicValueMap) Reset() {
	*x = DynamicValueMap{}
	mi := &file_kurrentdb_protocols_v2_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicValueMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicValueMap) ProtoMessage() {}

func (x *DynamicValueMap) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicValueMap.ProtoReflect.Descriptor instead.
func (*DynamicValueMap) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_core_proto_rawDescGZIP(), []int{2}
}

func (x *DynamicValueMap) GetValues() map[string]*DynamicValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// Represents a dynamic value
type DynamicValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*DynamicValue_NullValue
	//	*DynamicValue_Int32Value
	//	*DynamicValue_Int64Value
	//	*DynamicValue_BytesValue
	//	*DynamicValue_DoubleValue
	//	*DynamicValue_FloatValue
	//	*DynamicValue_StringValue
	//	*DynamicValue_BooleanValue
	//	*DynamicValue_TimestampValue
	//	*DynamicValue_DurationValue
	Kind          isDynamicValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicValue) Reset() {
	*x = DynamicValue{}
	mi := &file_kurrentdb_protocols_v2_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicValue) ProtoMessage() {}

func (x *DynamicValue) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicValue.ProtoReflect.Descriptor instead.
func (*DynamicValue) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_core_proto_rawDescGZIP(), []int{3}
}

func (x *DynamicValue) GetKind() isDynamicValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DynamicValue) GetNullValue() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_NullValue); ok {
			return x.NullValue
		}
	}
	return structpb.NullValue(0)
}

func (x *DynamicValue) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *DynamicValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *DynamicValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *DynamicValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *DynamicValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *DynamicValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *DynamicValue) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *DynamicValue) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *DynamicValue) GetDurationValue() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Kind.(*DynamicValue_DurationValue); ok {
			return x.DurationValue
		}
	}
	return nil
}

type isDynamicValue_Kind interface {
	isDynamicValue_Kind()
}

type DynamicValue_NullValue struct {
	// Represents a null value.
	NullValue structpb.NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

type DynamicValue_Int32Value struct {
	// Represents a 32-bit signed integer value.
	Int32Value int32 `protobuf:"zigzag32,2,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type DynamicValue_Int64Value struct {
	// Represents a 64-bit signed integer value.
	Int64Value int64 `protobuf:"zigzag64,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type DynamicValue_BytesValue struct {
	// Represents a byte array value.
	BytesValue []byte `protobuf:"bytes,4,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type DynamicValue_DoubleValue struct {
	// Represents a 64-bit double-precision floating-point value.
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type DynamicValue_FloatValue struct {
	// Represents a 32-bit single-precision floating-point value
	FloatValue float32 `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type DynamicValue_StringValue struct {
	// Represents a string value.
	StringValue string `protobuf:"bytes,7,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type DynamicValue_BooleanValue struct {
	// Represents a boolean value.
	BooleanValue bool `protobuf:"varint,8,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type DynamicValue_TimestampValue struct {
	// Represents a timestamp value.
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type DynamicValue_DurationValue struct {
	// Represents a duration value.
	DurationValue *durationpb.Duration `protobuf:"bytes,10,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

func (*DynamicValue_NullValue) isDynamicValue_Kind() {}

func (*DynamicValue_Int32Value) isDynamicValue_Kind() {}

func (*DynamicValue_Int64Value) isDynamicValue_Kind() {}

func (*DynamicValue_BytesValue) isDynamicValue_Kind() {}

func (*DynamicValue_DoubleValue) isDynamicValue_Kind() {}

func (*DynamicValue_FloatValue) isDynamicValue_Kind() {}

func (*DynamicValue_StringValue) isDynamicValue_Kind() {}

func (*DynamicValue_BooleanValue) isDynamicValue_Kind() {}

func (*DynamicValue_TimestampValue) isDynamicValue_Kind() {}

func (*DynamicValue_DurationValue) isDynamicValue_Kind() {}

var file_kurrentdb_protocols_v2_core_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ErrorAnnotations)(nil),
		Field:         50000,
		Name:          "kurrentdb.protocol.error_info",
		Tag:           "bytes,50000,opt,name=error_info",
		Filename:      "kurrentdb/protocols/v2/core.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Provides additional information about the error condition.
	//
	// optional kurrentdb.protocol.ErrorAnnotations error_info = 50000;
	E_ErrorInfo = &file_kurrentdb_protocols_v2_core_proto_extTypes[0]
)

var File_kurrentdb_protocols_v2_core_proto protoreflect.FileDescriptor

const file_kurrentdb_protocols_v2_core_proto_rawDesc = "" +
	"\n" +
	"!kurrentdb/protocols/v2/core.proto\x12\x12kurrentdb.protocol\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a google/protobuf/descriptor.proto\"\xc4\x01\n" +
	"\x10ErrorAnnotations\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12I\n" +
	"\bseverity\x18\x02 \x01(\x0e2-.kurrentdb.protocol.ErrorAnnotations.SeverityR\bseverity\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01\"&\n" +
	"\bSeverity\x12\x0f\n" +
	"\vRECOVERABLE\x10\x00\x12\t\n" +
	"\x05FATAL\x10\x01B\n" +
	"\n" +
	"\b_message\"L\n" +
	"\x10DynamicValueList\x128\n" +
	"\x06values\x18\x01 \x03(\v2 .kurrentdb.protocol.DynamicValueR\x06values\"\xb7\x01\n" +
	"\x0fDynamicValueMap\x12G\n" +
	"\x06values\x18\x01 \x03(\v2/.kurrentdb.protocol.DynamicValueMap.ValuesEntryR\x06values\x1a[\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .kurrentdb.protocol.DynamicValueR\x05value:\x028\x01\"\xdb\x03\n" +
	"\fDynamicValue\x12;\n" +
	"\n" +
	"null_value\x18\x01 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\tnullValue\x12!\n" +
	"\vint32_value\x18\x02 \x01(\x11H\x00R\n" +
	"int32Value\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x12H\x00R\n" +
	"int64Value\x12!\n" +
	"\vbytes_value\x18\x04 \x01(\fH\x00R\n" +
	"bytesValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vfloat_value\x18\x06 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fstring_value\x18\a \x01(\tH\x00R\vstringValue\x12%\n" +
	"\rboolean_value\x18\b \x01(\bH\x00R\fbooleanValue\x12E\n" +
	"\x0ftimestamp_value\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12B\n" +
	"\x0eduration_value\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationH\x00R\rdurationValueB\x06\n" +
	"\x04kind:i\n" +
	"\n" +
	"error_info\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\v2$.kurrentdb.protocol.ErrorAnnotationsR\terrorInfo\x88\x01\x01B\x81\x01\n" +
	"\x15io.kurrentdb.protocolP\x01ZQgithub.com/kurrent-io/KurrentDB-Client-Go/protos/kurrentdb/protocols/v2/core;core\xaa\x02\x12KurrentDB.Protocolb\x06proto3"

var (
	file_kurrentdb_protocols_v2_core_proto_rawDescOnce sync.Once
	file_kurrentdb_protocols_v2_core_proto_rawDescData []byte
)

func file_kurrentdb_protocols_v2_core_proto_rawDescGZIP() []byte {
	file_kurrentdb_protocols_v2_core_proto_rawDescOnce.Do(func() {
		file_kurrentdb_protocols_v2_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kurrentdb_protocols_v2_core_proto_rawDesc), len(file_kurrentdb_protocols_v2_core_proto_rawDesc)))
	})
	return file_kurrentdb_protocols_v2_core_proto_rawDescData
}

var file_kurrentdb_protocols_v2_core_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kurrentdb_protocols_v2_core_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kurrentdb_protocols_v2_core_proto_goTypes = []any{
	(ErrorAnnotations_Severity)(0),      // 0: kurrentdb.protocol.ErrorAnnotations.Severity
	(*ErrorAnnotations)(nil),            // 1: kurrentdb.protocol.ErrorAnnotations
	(*DynamicValueList)(nil),            // 2: kurrentdb.protocol.DynamicValueList
	(*DynamicValueMap)(nil),             // 3: kurrentdb.protocol.DynamicValueMap
	(*DynamicValue)(nil),                // 4: kurrentdb.protocol.DynamicValue
	nil,                                 // 5: kurrentdb.protocol.DynamicValueMap.ValuesEntry
	(structpb.NullValue)(0),             // 6: google.protobuf.NullValue
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 8: google.protobuf.Duration
	(*descriptorpb.MessageOptions)(nil), // 9: google.protobuf.MessageOptions
}
var file_kurrentdb_protocols_v2_core_proto_depIdxs = []int32{
	0, // 0: kurrentdb.protocol.ErrorAnnotations.severity:type_name -> kurrentdb.protocol.ErrorAnnotations.Severity
	4, // 1: kurrentdb.protocol.DynamicValueList.values:type_name -> kurrentdb.protocol.DynamicValue
	5, // 2: kurrentdb.protocol.DynamicValueMap.values:type_name -> kurrentdb.protocol.DynamicValueMap.ValuesEntry
	6, // 3: kurrentdb.protocol.DynamicValue.null_value:type_name -> google.protobuf.NullValue
	7, // 4: kurrentdb.protocol.DynamicValue.timestamp_value:type_name -> google.protobuf.Timestamp
	8, // 5: kurrentdb.protocol.DynamicValue.duration_value:type_name -> google.protobuf.Duration
	4, // 6: kurrentdb.protocol.DynamicValueMap.ValuesEntry.value:type_name -> kurrentdb.protocol.DynamicValue
	9, // 7: kurrentdb.protocol.error_info:extendee -> google.protobuf.MessageOptions
	1, // 8: kurrentdb.protocol.error_info:type_name -> kurrentdb.protocol.ErrorAnnotations
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	8, // [8:9] is the sub-list for extension type_name
	7, // [7:8] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_kurrentdb_protocols_v2_core_proto_init() }
func file_kurrentdb_protocols_v2_core_proto_init() {
	if File_kurrentdb_protocols_v2_core_proto != nil {
		return
	}
	file_kurrentdb_protocols_v2_core_proto_msgTypes[0].OneofWrappers = []any{}
	file_kurrentdb_protocols_v2_core_proto_msgTypes[3].OneofWrappers = []any{
		(*DynamicValue_NullValue)(nil),
		(*DynamicValue_Int32Value)(nil),
		(*DynamicValue_Int64Value)(nil),
		(*DynamicValue_BytesValue)(nil),
		(*DynamicValue_DoubleValue)(nil),
		(*DynamicValue_FloatValue)(nil),
		(*DynamicValue_StringValue)(nil),
		(*DynamicValue_BooleanValue)(nil),
		(*DynamicValue_TimestampValue)(nil),
		(*DynamicValue_DurationValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kurrentdb_protocols_v2_core_proto_rawDesc), len(file_kurrentdb_protocols_v2_core_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kurrentdb_protocols_v2_core_proto_goTypes,
		DependencyIndexes: file_kurrentdb_protocols_v2_core_proto_depIdxs,
		EnumInfos:         file_kurrentdb_protocols_v2_core_proto_enumTypes,
		MessageInfos:      file_kurrentdb_protocols_v2_core_proto_msgTypes,
		ExtensionInfos:    file_kurrentdb_protocols_v2_core_proto_extTypes,
	}.Build()
	File_kurrentdb_protocols_v2_core_proto = out.File
	file_kurrentdb_protocols_v2_core_proto_goTypes = nil
	file_kurrentdb_protocols_v2_core_proto_depIdxs = nil
}
