// ******************************************************************************************
// This protocol is UNSTABLE in the sense of being subject to change.
// ******************************************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.0
// source: kurrentdb/protocols/v2/streams/streams.proto

package streams

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the data format of the schema.
type SchemaFormat int32

const (
	// Default value, should not be used.
	SchemaFormat_SCHEMA_FORMAT_UNSPECIFIED SchemaFormat = 0
	SchemaFormat_SCHEMA_FORMAT_JSON        SchemaFormat = 1
	SchemaFormat_SCHEMA_FORMAT_PROTOBUF    SchemaFormat = 2
	SchemaFormat_SCHEMA_FORMAT_AVRO        SchemaFormat = 3
	SchemaFormat_SCHEMA_FORMAT_BYTES       SchemaFormat = 4
)

// Enum value maps for SchemaFormat.
var (
	SchemaFormat_name = map[int32]string{
		0: "SCHEMA_FORMAT_UNSPECIFIED",
		1: "SCHEMA_FORMAT_JSON",
		2: "SCHEMA_FORMAT_PROTOBUF",
		3: "SCHEMA_FORMAT_AVRO",
		4: "SCHEMA_FORMAT_BYTES",
	}
	SchemaFormat_value = map[string]int32{
		"SCHEMA_FORMAT_UNSPECIFIED": 0,
		"SCHEMA_FORMAT_JSON":        1,
		"SCHEMA_FORMAT_PROTOBUF":    2,
		"SCHEMA_FORMAT_AVRO":        3,
		"SCHEMA_FORMAT_BYTES":       4,
	}
)

func (x SchemaFormat) Enum() *SchemaFormat {
	p := new(SchemaFormat)
	*p = x
	return p
}

func (x SchemaFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_kurrentdb_protocols_v2_streams_streams_proto_enumTypes[0].Descriptor()
}

func (SchemaFormat) Type() protoreflect.EnumType {
	return &file_kurrentdb_protocols_v2_streams_streams_proto_enumTypes[0]
}

func (x SchemaFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaFormat.Descriptor instead.
func (SchemaFormat) EnumDescriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{0}
}

// Constants for expected revision validation in optimistic concurrency control.
// These can be used in the expected_revision field, or you can specify an actual revision number.
type ExpectedRevisionConstants int32

const (
	// The stream must have exactly one event at revision 0.
	// Used for scenarios requiring strict single-event semantics.
	ExpectedRevisionConstants_EXPECTED_REVISION_CONSTANTS_SINGLE_EVENT ExpectedRevisionConstants = 0
	// The stream must not exist yet (first write to the stream).
	// Fails if the stream already has events.
	ExpectedRevisionConstants_EXPECTED_REVISION_CONSTANTS_NO_STREAM ExpectedRevisionConstants = -1
	// Accept any current state of the stream (no optimistic concurrency check).
	// The write will succeed regardless of the stream's current revision.
	ExpectedRevisionConstants_EXPECTED_REVISION_CONSTANTS_ANY ExpectedRevisionConstants = -2
	// The stream must exist (have at least one record).
	// Fails if the stream doesn't exist yet.
	ExpectedRevisionConstants_EXPECTED_REVISION_CONSTANTS_EXISTS ExpectedRevisionConstants = -4
)

// Enum value maps for ExpectedRevisionConstants.
var (
	ExpectedRevisionConstants_name = map[int32]string{
		0:  "EXPECTED_REVISION_CONSTANTS_SINGLE_EVENT",
		-1: "EXPECTED_REVISION_CONSTANTS_NO_STREAM",
		-2: "EXPECTED_REVISION_CONSTANTS_ANY",
		-4: "EXPECTED_REVISION_CONSTANTS_EXISTS",
	}
	ExpectedRevisionConstants_value = map[string]int32{
		"EXPECTED_REVISION_CONSTANTS_SINGLE_EVENT": 0,
		"EXPECTED_REVISION_CONSTANTS_NO_STREAM":    -1,
		"EXPECTED_REVISION_CONSTANTS_ANY":          -2,
		"EXPECTED_REVISION_CONSTANTS_EXISTS":       -4,
	}
)

func (x ExpectedRevisionConstants) Enum() *ExpectedRevisionConstants {
	p := new(ExpectedRevisionConstants)
	*p = x
	return p
}

func (x ExpectedRevisionConstants) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExpectedRevisionConstants) Descriptor() protoreflect.EnumDescriptor {
	return file_kurrentdb_protocols_v2_streams_streams_proto_enumTypes[1].Descriptor()
}

func (ExpectedRevisionConstants) Type() protoreflect.EnumType {
	return &file_kurrentdb_protocols_v2_streams_streams_proto_enumTypes[1]
}

func (x ExpectedRevisionConstants) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExpectedRevisionConstants.Descriptor instead.
func (ExpectedRevisionConstants) EnumDescriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{1}
}

// Represents the input for appending records to a specific stream.
type AppendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stream to append records to.
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// The records to append to the stream.
	Records []*AppendRecord `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	// The expected revision for optimistic concurrency control.
	// Can be either:
	// - A specific revision number (0, 1, 2, ...) - the stream must be at exactly this revision
	// - An ExpectedRevisionConstants value (-4, -2, -1) for special semantics
	//
	// If omitted, defaults to EXPECTED_REVISION_CONSTANTS_ANY (-2).
	ExpectedRevision *int64 `protobuf:"zigzag64,3,opt,name=expected_revision,json=expectedRevision,proto3,oneof" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{0}
}

func (x *AppendRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *AppendRequest) GetRecords() []*AppendRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *AppendRequest) GetExpectedRevision() int64 {
	if x != nil && x.ExpectedRevision != nil {
		return *x.ExpectedRevision
	}
	return 0
}

// Represents the outcome of an append operation.
type AppendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stream to which records were appended.
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// The actual/current revision of the stream after the append.
	// This is the revision number of the last record written to this stream.
	StreamRevision int64 `protobuf:"zigzag64,2,opt,name=stream_revision,json=streamRevision,proto3" json:"stream_revision,omitempty"`
	// The position of the last appended record in the global log.
	Position      *int64 `protobuf:"zigzag64,3,opt,name=position,proto3,oneof" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{1}
}

func (x *AppendResponse) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *AppendResponse) GetStreamRevision() int64 {
	if x != nil {
		return x.StreamRevision
	}
	return 0
}

func (x *AppendResponse) GetPosition() int64 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

type AppendSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The results of each append request in the session.
	Output []*AppendResponse `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
	// The global commit position of the last appended record in the session.
	Position      int64 `protobuf:"zigzag64,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendSessionResponse) Reset() {
	*x = AppendSessionResponse{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendSessionResponse) ProtoMessage() {}

func (x *AppendSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendSessionResponse.ProtoReflect.Descriptor instead.
func (*AppendSessionResponse) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{2}
}

func (x *AppendSessionResponse) GetOutput() []*AppendResponse {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *AppendSessionResponse) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

// Schema information for record validation and interpretation.
type SchemaInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The format of the data payload.
	// Determines how the bytes in AppendRecord.data should be interpreted.
	Format SchemaFormat `protobuf:"varint,1,opt,name=format,proto3,enum=kurrentdb.protocol.v2.streams.SchemaFormat" json:"format,omitempty"`
	// The schema name (replaces the legacy "event type" concept).
	// Identifies what kind of data this record contains.
	//
	// Common naming formats:
	//   - Kebab-case: "order-placed", "customer-registered"
	//   - URN format: "urn:kurrentdb:events:order-placed:v1"
	//   - Dotted namespace: "Teams.Player.V1", "Orders.OrderPlaced.V2"
	//   - Reverse domain: "com.acme.orders.placed"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The identifier of the specific version of the schema that the record payload
	// conforms to. This should match a registered schema version in the system.
	// Not necessary when not enforcing schema validation.
	Id            *string `protobuf:"bytes,3,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaInfo) Reset() {
	*x = SchemaInfo{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaInfo) ProtoMessage() {}

func (x *SchemaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaInfo.ProtoReflect.Descriptor instead.
func (*SchemaInfo) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{3}
}

func (x *SchemaInfo) GetFormat() SchemaFormat {
	if x != nil {
		return x.Format
	}
	return SchemaFormat_SCHEMA_FORMAT_UNSPECIFIED
}

func (x *SchemaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaInfo) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

// Record to be appended to a stream.
type AppendRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this record (must be a valid UUID/GUID).
	// If not provided, the server will generate a new one.
	RecordId *string `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3,oneof" json:"record_id,omitempty"`
	// A collection of properties providing additional information about the
	// record. Can contain user-defined or system propreties.
	// System keys will be prefixed with "$" (e.g., "$timestamp").
	// User-defined keys MUST NOT start with "$".
	//
	// Common examples:
	//
	//	User metadata:
	//	  - "user-id": "12345"
	//	  - "tenant": "acme-corp"
	//	  - "source": "mobile-app"
	//
	//	System metadata (with $ prefix):
	//	  - "$trace-id": "4bf92f3577b34da6a3ce929d0e0e4736"  // OpenTelemetry trace ID
	//	  - "$span-id": "00f067aa0ba902b7"                   // OpenTelemetry span ID
	//	  - "$timestamp": "2025-01-15T10:30:00.000Z"         // ISO 8601 timestamp
	Properties map[string]*structpb.Value `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Schema information for this record.
	Schema *SchemaInfo `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	// The record payload as raw bytes.
	// The format specified in SchemaInfo determines how to interpret these bytes.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// Target stream for this record.
	// Required for AppendRecords (each record specifies its own stream).
	// Ignored for AppendSession (the stream is specified in AppendRequest).
	Stream        string `protobuf:"bytes,5,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRecord) Reset() {
	*x = AppendRecord{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRecord) ProtoMessage() {}

func (x *AppendRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRecord.ProtoReflect.Descriptor instead.
func (*AppendRecord) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{4}
}

func (x *AppendRecord) GetRecordId() string {
	if x != nil && x.RecordId != nil {
		return *x.RecordId
	}
	return ""
}

func (x *AppendRecord) GetProperties() map[string]*structpb.Value {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *AppendRecord) GetSchema() *SchemaInfo {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *AppendRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppendRecord) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

// Request to append records to one or more streams atomically.
//
// All records are committed in a single transaction. Each record specifies its
// target stream via AppendRecord.stream. Consistency checks are evaluated before
// any records are written.
type AppendRecordsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The records to append. Records targeting the same stream maintain their
	// order from this list.
	Records []*AppendRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// Optional consistency checks evaluated before commit. If any check fails,
	// the entire transaction is aborted.
	Checks        []*ConsistencyCheck `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRecordsRequest) Reset() {
	*x = AppendRecordsRequest{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRecordsRequest) ProtoMessage() {}

func (x *AppendRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRecordsRequest.ProtoReflect.Descriptor instead.
func (*AppendRecordsRequest) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{5}
}

func (x *AppendRecordsRequest) GetRecords() []*AppendRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *AppendRecordsRequest) GetChecks() []*ConsistencyCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

// Response from a successful AppendRecords operation.
//
// Contains the resulting revision for each stream that was written to and the
// global commit position of the transaction.
type AppendRecordsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resulting revision for each stream that received records. One entry per
	// distinct stream written to, in no guaranteed order.
	Revisions []*StreamRevision `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	// The global commit position of the last record written in this transaction.
	// Can be used for read-your-writes consistency or progress tracking.
	Position      int64 `protobuf:"zigzag64,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRecordsResponse) Reset() {
	*x = AppendRecordsResponse{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRecordsResponse) ProtoMessage() {}

func (x *AppendRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRecordsResponse.ProtoReflect.Descriptor instead.
func (*AppendRecordsResponse) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{6}
}

func (x *AppendRecordsResponse) GetRevisions() []*StreamRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

func (x *AppendRecordsResponse) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

// A pre-commit condition that must hold true for the transaction to succeed.
//
// Consistency checks are evaluated atomically before any records are written. If
// any check is violated, the entire transaction is aborted.
type ConsistencyCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ConsistencyCheck_StreamState
	Type          isConsistencyCheck_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsistencyCheck) Reset() {
	*x = ConsistencyCheck{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsistencyCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistencyCheck) ProtoMessage() {}

func (x *ConsistencyCheck) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistencyCheck.ProtoReflect.Descriptor instead.
func (*ConsistencyCheck) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{7}
}

func (x *ConsistencyCheck) GetType() isConsistencyCheck_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ConsistencyCheck) GetStreamState() *ConsistencyCheck_StreamStateCheck {
	if x != nil {
		if x, ok := x.Type.(*ConsistencyCheck_StreamState); ok {
			return x.StreamState
		}
	}
	return nil
}

type isConsistencyCheck_Type interface {
	isConsistencyCheck_Type()
}

type ConsistencyCheck_StreamState struct {
	// Check that a stream is at a specific revision or lifecycle state.
	StreamState *ConsistencyCheck_StreamStateCheck `protobuf:"bytes,1,opt,name=stream_state,json=streamState,proto3,oneof"`
}

func (*ConsistencyCheck_StreamState) isConsistencyCheck_Type() {}

// A specific revision of a stream.
type StreamRevision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream name.
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// Revision within the stream.
	Revision      int64 `protobuf:"zigzag64,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRevision) Reset() {
	*x = StreamRevision{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRevision) ProtoMessage() {}

func (x *StreamRevision) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRevision.ProtoReflect.Descriptor instead.
func (*StreamRevision) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{8}
}

func (x *StreamRevision) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *StreamRevision) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// Asserts a stream is at a specific revision or lifecycle state before commit.
type ConsistencyCheck_StreamStateCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stream name.
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// The expected state of the stream (revision number or state constant).
	ExpectedState int64 `protobuf:"zigzag64,2,opt,name=expected_state,json=expectedState,proto3" json:"expected_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsistencyCheck_StreamStateCheck) Reset() {
	*x = ConsistencyCheck_StreamStateCheck{}
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsistencyCheck_StreamStateCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistencyCheck_StreamStateCheck) ProtoMessage() {}

func (x *ConsistencyCheck_StreamStateCheck) ProtoReflect() protoreflect.Message {
	mi := &file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistencyCheck_StreamStateCheck.ProtoReflect.Descriptor instead.
func (*ConsistencyCheck_StreamStateCheck) Descriptor() ([]byte, []int) {
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ConsistencyCheck_StreamStateCheck) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ConsistencyCheck_StreamStateCheck) GetExpectedState() int64 {
	if x != nil {
		return x.ExpectedState
	}
	return 0
}

var File_kurrentdb_protocols_v2_streams_streams_proto protoreflect.FileDescriptor

const file_kurrentdb_protocols_v2_streams_streams_proto_rawDesc = "" +
	"\n" +
	",kurrentdb/protocols/v2/streams/streams.proto\x12\x1dkurrentdb.protocol.v2.streams\x1a\x1cgoogle/protobuf/struct.proto\"\xb6\x01\n" +
	"\rAppendRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12E\n" +
	"\arecords\x18\x02 \x03(\v2+.kurrentdb.protocol.v2.streams.AppendRecordR\arecords\x120\n" +
	"\x11expected_revision\x18\x03 \x01(\x12H\x00R\x10expectedRevision\x88\x01\x01B\x14\n" +
	"\x12_expected_revision\"\x7f\n" +
	"\x0eAppendResponse\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12'\n" +
	"\x0fstream_revision\x18\x02 \x01(\x12R\x0estreamRevision\x12\x1f\n" +
	"\bposition\x18\x03 \x01(\x12H\x00R\bposition\x88\x01\x01B\v\n" +
	"\t_position\"z\n" +
	"\x15AppendSessionResponse\x12E\n" +
	"\x06output\x18\x01 \x03(\v2-.kurrentdb.protocol.v2.streams.AppendResponseR\x06output\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x12R\bposition\"\x81\x01\n" +
	"\n" +
	"SchemaInfo\x12C\n" +
	"\x06format\x18\x01 \x01(\x0e2+.kurrentdb.protocol.v2.streams.SchemaFormatR\x06format\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"\xe1\x02\n" +
	"\fAppendRecord\x12 \n" +
	"\trecord_id\x18\x01 \x01(\tH\x00R\brecordId\x88\x01\x01\x12[\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2;.kurrentdb.protocol.v2.streams.AppendRecord.PropertiesEntryR\n" +
	"properties\x12A\n" +
	"\x06schema\x18\x03 \x01(\v2).kurrentdb.protocol.v2.streams.SchemaInfoR\x06schema\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\tR\x06stream\x1aU\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_record_id\"\xa6\x01\n" +
	"\x14AppendRecordsRequest\x12E\n" +
	"\arecords\x18\x01 \x03(\v2+.kurrentdb.protocol.v2.streams.AppendRecordR\arecords\x12G\n" +
	"\x06checks\x18\x02 \x03(\v2/.kurrentdb.protocol.v2.streams.ConsistencyCheckR\x06checks\"\x80\x01\n" +
	"\x15AppendRecordsResponse\x12K\n" +
	"\trevisions\x18\x01 \x03(\v2-.kurrentdb.protocol.v2.streams.StreamRevisionR\trevisions\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x12R\bposition\"\xd4\x01\n" +
	"\x10ConsistencyCheck\x12e\n" +
	"\fstream_state\x18\x01 \x01(\v2@.kurrentdb.protocol.v2.streams.ConsistencyCheck.StreamStateCheckH\x00R\vstreamState\x1aQ\n" +
	"\x10StreamStateCheck\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12%\n" +
	"\x0eexpected_state\x18\x02 \x01(\x12R\rexpectedStateB\x06\n" +
	"\x04type\"D\n" +
	"\x0eStreamRevision\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x12R\brevision*\x92\x01\n" +
	"\fSchemaFormat\x12\x1d\n" +
	"\x19SCHEMA_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SCHEMA_FORMAT_JSON\x10\x01\x12\x1a\n" +
	"\x16SCHEMA_FORMAT_PROTOBUF\x10\x02\x12\x16\n" +
	"\x12SCHEMA_FORMAT_AVRO\x10\x03\x12\x17\n" +
	"\x13SCHEMA_FORMAT_BYTES\x10\x04*\xdc\x01\n" +
	"\x19ExpectedRevisionConstants\x12,\n" +
	"(EXPECTED_REVISION_CONSTANTS_SINGLE_EVENT\x10\x00\x122\n" +
	"%EXPECTED_REVISION_CONSTANTS_NO_STREAM\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12,\n" +
	"\x1fEXPECTED_REVISION_CONSTANTS_ANY\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12/\n" +
	"\"EXPECTED_REVISION_CONSTANTS_EXISTS\x10\xfc\xff\xff\xff\xff\xff\xff\xff\xff\x012\x83\x02\n" +
	"\x0eStreamsService\x12u\n" +
	"\rAppendSession\x12,.kurrentdb.protocol.v2.streams.AppendRequest\x1a4.kurrentdb.protocol.v2.streams.AppendSessionResponse(\x01\x12z\n" +
	"\rAppendRecords\x123.kurrentdb.protocol.v2.streams.AppendRecordsRequest\x1a4.kurrentdb.protocol.v2.streams.AppendRecordsResponseBQZOgithub.com/kurrent-io/KurrentDB-Client-Go/protos/kurrentdb/protocols/v2/streamsb\x06proto3"

var (
	file_kurrentdb_protocols_v2_streams_streams_proto_rawDescOnce sync.Once
	file_kurrentdb_protocols_v2_streams_streams_proto_rawDescData []byte
)

func file_kurrentdb_protocols_v2_streams_streams_proto_rawDescGZIP() []byte {
	file_kurrentdb_protocols_v2_streams_streams_proto_rawDescOnce.Do(func() {
		file_kurrentdb_protocols_v2_streams_streams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kurrentdb_protocols_v2_streams_streams_proto_rawDesc), len(file_kurrentdb_protocols_v2_streams_streams_proto_rawDesc)))
	})
	return file_kurrentdb_protocols_v2_streams_streams_proto_rawDescData
}

var file_kurrentdb_protocols_v2_streams_streams_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_kurrentdb_protocols_v2_streams_streams_proto_goTypes = []any{
	(SchemaFormat)(0),                         // 0: kurrentdb.protocol.v2.streams.SchemaFormat
	(ExpectedRevisionConstants)(0),            // 1: kurrentdb.protocol.v2.streams.ExpectedRevisionConstants
	(*AppendRequest)(nil),                     // 2: kurrentdb.protocol.v2.streams.AppendRequest
	(*AppendResponse)(nil),                    // 3: kurrentdb.protocol.v2.streams.AppendResponse
	(*AppendSessionResponse)(nil),             // 4: kurrentdb.protocol.v2.streams.AppendSessionResponse
	(*SchemaInfo)(nil),                        // 5: kurrentdb.protocol.v2.streams.SchemaInfo
	(*AppendRecord)(nil),                      // 6: kurrentdb.protocol.v2.streams.AppendRecord
	(*AppendRecordsRequest)(nil),              // 7: kurrentdb.protocol.v2.streams.AppendRecordsRequest
	(*AppendRecordsResponse)(nil),             // 8: kurrentdb.protocol.v2.streams.AppendRecordsResponse
	(*ConsistencyCheck)(nil),                  // 9: kurrentdb.protocol.v2.streams.ConsistencyCheck
	(*StreamRevision)(nil),                    // 10: kurrentdb.protocol.v2.streams.StreamRevision
	nil,                                       // 11: kurrentdb.protocol.v2.streams.AppendRecord.PropertiesEntry
	(*ConsistencyCheck_StreamStateCheck)(nil), // 12: kurrentdb.protocol.v2.streams.ConsistencyCheck.StreamStateCheck
	(*structpb.Value)(nil),                    // 13: google.protobuf.Value
}
var file_kurrentdb_protocols_v2_streams_streams_proto_depIdxs = []int32{
	6,  // 0: kurrentdb.protocol.v2.streams.AppendRequest.records:type_name -> kurrentdb.protocol.v2.streams.AppendRecord
	3,  // 1: kurrentdb.protocol.v2.streams.AppendSessionResponse.output:type_name -> kurrentdb.protocol.v2.streams.AppendResponse
	0,  // 2: kurrentdb.protocol.v2.streams.SchemaInfo.format:type_name -> kurrentdb.protocol.v2.streams.SchemaFormat
	11, // 3: kurrentdb.protocol.v2.streams.AppendRecord.properties:type_name -> kurrentdb.protocol.v2.streams.AppendRecord.PropertiesEntry
	5,  // 4: kurrentdb.protocol.v2.streams.AppendRecord.schema:type_name -> kurrentdb.protocol.v2.streams.SchemaInfo
	6,  // 5: kurrentdb.protocol.v2.streams.AppendRecordsRequest.records:type_name -> kurrentdb.protocol.v2.streams.AppendRecord
	9,  // 6: kurrentdb.protocol.v2.streams.AppendRecordsRequest.checks:type_name -> kurrentdb.protocol.v2.streams.ConsistencyCheck
	10, // 7: kurrentdb.protocol.v2.streams.AppendRecordsResponse.revisions:type_name -> kurrentdb.protocol.v2.streams.StreamRevision
	12, // 8: kurrentdb.protocol.v2.streams.ConsistencyCheck.stream_state:type_name -> kurrentdb.protocol.v2.streams.ConsistencyCheck.StreamStateCheck
	13, // 9: kurrentdb.protocol.v2.streams.AppendRecord.PropertiesEntry.value:type_name -> google.protobuf.Value
	2,  // 10: kurrentdb.protocol.v2.streams.StreamsService.AppendSession:input_type -> kurrentdb.protocol.v2.streams.AppendRequest
	7,  // 11: kurrentdb.protocol.v2.streams.StreamsService.AppendRecords:input_type -> kurrentdb.protocol.v2.streams.AppendRecordsRequest
	4,  // 12: kurrentdb.protocol.v2.streams.StreamsService.AppendSession:output_type -> kurrentdb.protocol.v2.streams.AppendSessionResponse
	8,  // 13: kurrentdb.protocol.v2.streams.StreamsService.AppendRecords:output_type -> kurrentdb.protocol.v2.streams.AppendRecordsResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_kurrentdb_protocols_v2_streams_streams_proto_init() }
func file_kurrentdb_protocols_v2_streams_streams_proto_init() {
	if File_kurrentdb_protocols_v2_streams_streams_proto != nil {
		return
	}
	file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[0].OneofWrappers = []any{}
	file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[1].OneofWrappers = []any{}
	file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[3].OneofWrappers = []any{}
	file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[4].OneofWrappers = []any{}
	file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes[7].OneofWrappers = []any{
		(*ConsistencyCheck_StreamState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kurrentdb_protocols_v2_streams_streams_proto_rawDesc), len(file_kurrentdb_protocols_v2_streams_streams_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kurrentdb_protocols_v2_streams_streams_proto_goTypes,
		DependencyIndexes: file_kurrentdb_protocols_v2_streams_streams_proto_depIdxs,
		EnumInfos:         file_kurrentdb_protocols_v2_streams_streams_proto_enumTypes,
		MessageInfos:      file_kurrentdb_protocols_v2_streams_streams_proto_msgTypes,
	}.Build()
	File_kurrentdb_protocols_v2_streams_streams_proto = out.File
	file_kurrentdb_protocols_v2_streams_streams_proto_goTypes = nil
	file_kurrentdb_protocols_v2_streams_streams_proto_depIdxs = nil
}
