name: Build and lint

on:
  workflow_call:
    outputs:
      go_version:
        description: "Go version to be used"
        value: ${{ jobs.build.outputs.go_version }}

jobs:
  go-version:
    name: Get Go version
    uses: ./.github/workflows/go-version.yml

  build:
    name: Code generation & compile
    needs: go-version
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-2019, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.go-version.outputs.go_version }}
      - name: Generate protos and build project
        run: make generate-protos-and-build
    outputs:
      go_version: ${{ needs.go-version.outputs.go_version }}

  linting:
    needs: build
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        run: go vet ./...
      - name: Code formatting checks
        run: diff -u <(echo -n) <(goimports -d ./)

