name: "QA"

on:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
        default: "ci"
        description: "The tag to use for the docker image"
      image:
        required: false
        type: string
        default: "kurrentdb"
        description: "The docker image to use"
      registry:
        required: false
        type: string
        default: "docker.kurrent.io/kurrent-staging"
        description: "The docker registry to use"

jobs:
  build-and-lint:
    name: Build and lint
    uses: ./.github/workflows/build-and-lint.yml

  test:
    needs: build-and-lint
    name: QA
    uses: ./.github/workflows/tests.yml
    with:
      image: ${{ inputs.image }}
      tag: ${{ inputs.tag }}
      registry: ${{ inputs.registry }}
      go_version: ${{ needs.go-version.outputs.go_version }}
    secrets: inherit
