name: Tests

on:
  workflow_call:
    inputs:
      runtime:
        required: true
        type: string

      go_version:
        required: true
        type: string

      registry:
        description: "When in QA mode, the Docker registry to use"
        type: string
        required: false

      image:
        description: "When in QA mode, the Docker image to use"
        type: string
        required: false

      tag:
        description: "When in QA mode, the Docker image tag to use"
        type: string
        required: false

jobs:
  load_configuration:
    uses: ./.github/workflows/load-configuration.yml
    with:
      runtime: ${{ inputs.runtime }}
      registry: ${{ inputs.registry }}
      image: ${{ inputs.image }}
      tag: ${{ inputs.tag }}

  test:
    needs: load_configuration
    name: Test
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        test: [ Streams, PersistentSubscriptions, Projections ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}

      - name: Login to Cloudsmith
        uses: docker/login-action@v3
        with:
          registry: docker.kurrent.io
          username: ${{ secrets.CLOUDSMITH_CICD_USER }}
          password: ${{ secrets.CLOUDSMITH_CICD_TOKEN }}

      - name: Misc tests
        run: go test --count=1 -v ./kurrentdb -run TestMisc

      - name: Start KurrentDB
        run: make start-kurrentdb
        env:
          KURRENTDB_DOCKER_REGISTRY: ${{ needs.load_configuration.outputs.registry }}
          KURRENTDB_DOCKER_IMAGE: ${{ needs.load_configuration.outputs.image }}
          KURRENTDB_DOCKER_TAG: ${{ needs.load_configuration.outputs.tag }}

      - name: Run Go Tests
        run: go test --count=1 -v ./test -run Test${{ matrix.test }}