name: "Dispatch"

on:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string
        default: "ci"
      image:
        required: false
        type: string
        default: "kurrentdb"
      registry:
        required: false
        type: string
        default: "docker.kurrent.io/kurrent-staging"

jobs:
  go-version:
    uses: ./.github/workflows/go-version.yml

  test:
    needs: go-version
    name: Test
    uses: ./.github/workflows/tests.yml
    with:
      image: ${{ inputs.image }}
      tag: ${{ inputs.tag }}
      registry: ${{ inputs.registry }}
      go_version: ${{ needs.go-version.outputs.go_version }}

  plugins-tests:
    needs: go-version
    name: Plugins Tests
    uses: ./.github/workflows/test-plugins.yml
    with:
      tag: ${{ inputs.tag }}
      image: eventstoredb-commercial
      registry: "docker.eventstore.com/eventstore-ee"
      go_version: ${{ needs.go-version.outputs.go_version }}
    secrets: inherit
