name: tests workflow

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string

      tag:
        required: true
        type: string

      image:
        required: true
        type: string

      go_version:
        required: true
        type: string

jobs:
  test:
    name: Test
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        test: [Streams, PersistentSubscriptions, Projections]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}

      - name: Start KurrentDB clusters, insecure and secure node
        run: make start-kurrentdb
        env:
          EVENTSTORE_DOCKER_TAG: ${{ inputs.tag }}
          EVENTSTORE_DOCKER_REGISTRY: ${{ inputs.registry }}
          EVENTSTORE_DOCKER_IMAGE: ${{ inputs.image }}

      - name: Run Go Tests
        run: go test --count=1 -v ./kurrentdb -run Test${{ matrix.test }}